// Generated by mau from Item.mau - do not edit.
// mau · Copyright (c) 2026 hexedmaya · mau License 1.0
import { signal, computed, effect, untracked, batch, onDestroy, router, route, navigate, h as __h, raw as __raw, each as __each, adoptStyle as __style } from "../index.js";

export default function Item(props = {}) {
  const __root = __h("li", {  }, () => (props.label));
  return __root;
}
